import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'
import Wrapper from "./wrapper";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Test Application",
	description: "Generated by create next app version 14",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Wrapper>
					{children}
				</Wrapper>
			</body>
			<GoogleAnalytics gaId="G-XYZ" />
		</html>
	);
}